name: linting, testing, building
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  pipeline:
    runs-on: windows-2019
    strategy:
      matrix:
        node-version: [16.x]

    spetps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-versions: ${{ matrix.node-version }}
      - name: install modules
        run: npm install