name: linting, testing, building
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  pipeline:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [16.13.2]

    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-versions: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: building production project
        run: npm run prodBuild
      - name: linting typescript
        run: npm run lintts
      - name: linting scss
        run: npm run lintstyle
      - name: unit tests
        run: npm run unit