name: linting, testing, building
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  pipeline:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: build production project
        run: npm run prodBuild
      - name: linting typescript
        run: npm run lintts
      - name: linting css
        if: always()
        run: npm run lintstyle
      - name: unit testing
        if: always()
        run: npm run unit
      - name: build storybook
        if: always()
        run: npm run build-storybook
      - name: screenshot testing
        if: always()
        run: npm run testuici